
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: scplant-frontend-web
    container_name: "scplant-frontend-web"
    command: sh -c "export PORT=80 && npm start"
    tty: true
    restart: always
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
      # - ./node_modules:/usr/src/app/node_modules
    # expose: 
    #   - 5049
    ports:
      - '127.0.0.1:5049:80'
     # - '5049:3355'
    networks:
      - default
      - scplant-network


networks:
  scplant-network:
    external: true

