
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: scplant_frontend_web
    container_name: "scplant_frontend_web"
    command: sh -c "export PORT=3355 && npm start"
    tty: true
    restart: always
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
      # - ./node_modules:/usr/src/app/node_modules
    expose: 
      - 5049
    ports:
      - '5049:3355'
    networks:
      - default
