version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "scPlant_frontend"
    command: sh -c "export PORT=3355 && npm start"
    tty: true
    restart: always
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
    expose: 
      - 8080
    ports:
     # - '127.0.0.1:9090:80'
      - '8080:3355'
    networks:
      - default
      - kbc-net

networks:
  kbc-net:
    external: true